### PR TITLE
Fix module load on galp3

### PR DESCRIPTION
**Pull request by tleydxdy**
justs like https://github.com/pop-os/system76-dkms/pull/36 on galp3 the system fails to load the module, and the fix works as well.

### CODE REVIEW

**Comment by jackpot51** [comment]
Is your firmware up to date?

**Comment by tleydxdy** [comment]
> Is your firmware up to date?

it is currently 1.05.03MI1

realized the firmware-cli would try to install and flash even when the firmware is already up to date. that caused some, problems...

**Comment by jacobgkau** [comment]
We don't currently have a galp3 in the lab, but we do have a galp2 and a bonw13. Testing shows that galp2 and bonw13 also need to be changed to the `DMI_TABLE` function instead of `DMI_TABLE_LEGACY`. After changing:

- galp2: Airplane mode key now shows on-screen notification when toggled, airplane mode LED still works, sensor output now present.
- bonw13: Airplane mode key now shows on-screen notification when toggled, airplane mode LED still works, sensor output now present, keyboard LEDs now controllable via software (still no overlays when adjusted via hotkeys.)

I've gone ahead and removed the `DMI_TABLE_LEGACY` function since it's no longer used by any products. I'm not sure of the history behind this, but it seems like our firmware originally used a different `DMI_BIOS_VENDOR`, started using `System76` as the vendor when the DKMS module was created, then later stopped using `System76` as the vendor again (which makes sense, since we now have Open Firmware which we're much more of a "vendor" for.)

**Review by jacobgkau — APPROVED** [review]

**Comment by jackpot51** [comment]
@jacobgkau we had these set a specific way so that firmware that implements these functions itself is not overridden by software. Older firmware was done this way. I'm not completely confident in having both firmware and software control these settings at the same time.

**Comment by jacobgkau** [comment]
@jackpot51 The reason #54 and #36 were opened was because the firmware was not providing equivalent functionality. Do you think we should remove the functions that firmware handles, e.g. remove `DRIVER_AP_LED` from galp2/3 since the airplane LED works without it?

**Comment by jackpot51** [comment]
@jacobgkau The firmware functions that are overlapping do not include being able to set the keyboard backlights from a script like https://github.com/pop-os/system76-dkms/pull/36 requested. So removing as many functions as possible while retaining that might be okay.

**Comment by jacobgkau** [comment]
@jackpot51 I've removed everything except for `DRIVER_HWMON` from galp2/galp3 (they're missing sensor output without it), and that plus `DRIVER_KB_LED` for bonw13 since it enables keyboard color control. (galp2/3 did not previously have the keyboard LED function.) Those are the only three products being changed.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]

**Comment by jacobgkau** [comment]
Re-confirmed airplane key and LED works on galp2 and bonw13.

**Pull request merged**
