### PR TITLE
Fix: Make it work again on `oryp3-ess`

### PR DESCRIPTION
**Pull request by zaufi**
I have this model, and after update this driver it just stop working for me.
So, here is a patch to make it work again.

### CODE REVIEW

**Comment by leviport** [comment]
Hi @zaufi , thanks for the PR! I'm also working on an oryp3-ess, but I'm not seeing any issues with any drivers. What issues were you running into?

**Comment by zaufi** [comment]
Ok, I'll check it again soon. I do not recall the exact message, but it was about "this driver doesn't suite for your model" or smth similar...

**Comment by leviport** [comment]
Hi @zaufi, just wanted to follow up: did you get a chance to check up on this driver issue again?

**Comment by leviport** [comment]
I'm going to close this for now, but we can definitely revisit and reopen the issue later if need be.

**Comment by zaufi** [comment]
With the current `master` I'm still have the error:
```
[  +0.002516] system76: Model does not utilize this driver
```

**Comment by zaufi** [comment]
@leviport Dunno how to reopen this PR...

**Comment by leviport** [comment]
Hi @zaufi , this PR has been reopened. However I'll still need more information in order to test your fix. Where are you seeing this error?

**Comment by zaufi** [comment]
> Hi @zaufi , this PR has been reopened. However I'll still need more information in order to test your fix. Where are you seeing this error?

I see it in `dmesg` log.

**Comment by jackpot51** [comment]
The oryp3-ess is supported by firmware and does not require this kernel driver. What features from this driver are you missing without it?

**Comment by zaufi** [comment]
> The oryp3-ess is supported by firmware and does not require this kernel driver. What features from this driver are you missing without it?

The keyboard backlight doesn't work w/ this.

**Comment by leviport** [comment]
@zaufi I've followed up with our support team and they haven't heard reports of the keyboard backlight issue, and my own oryp3-ess keyboard's backlight is also working as expected. Since the backlight is controlled by firmware, I'm wondering if your firmware is out of date. Can you check your firmware and EC versions? The current firmware version is `1.05.02dRSA2` and the current EC version is `1.05.05MI1`. Can you also let us know which version of Pop!_OS you're running, and which kernel?

**Comment by zaufi** [comment]
@leviport 
```
[  +0.000000] DMI:  System76  Oryx Pro/ Oryx Pro, BIOS 1.05.02dRSA2 02/20/2017
```
I'm running Exherbo Linux and the kernel 5.5.x.
Gonna check the firmware on the next reboot...

**Comment by zaufi** [comment]
I've checked the EC version. It is 1.05.05MI1.

**Comment by leviport** [comment]
Hi @zaufi 

It does appear that you are on the newest BIOS and EC versions. Since the oryp3-ess keyboard backlight controls should be controlled by firmware and we have not heard any other reports of this issue, I would rather not merge a fix into master that isn't required by any other users.

**Pull request closed without merging**
