### PR TITLE
Add kudu6

### PR DESCRIPTION
**Pull request by crawfxrd**

### CODE REVIEW

**Comment by jackpot51** [comment]
I think this should be DRIVER_AP_WMI as well, like the pangolins

**Review by jackpot51 — DISMISSED** [review]

**Review by bflanagin — APPROVED** [review]
dmidecode reports kudu6

**Comment by crawfxrd** [comment]
Pushed new commit to force CI to run again, since it was stuck on required checks.

**Review by jackpot51 — APPROVED** [review]

**Comment by crawfxrd** [comment]
`groovy` builds need to be disabled.

**Review by leviport — APPROVED** [review]

**Pull request merged**
